# Where things are
collections:
  my_categories:
    output: true
    permalink: /category/:name/
  my_tags:
    output: true
    permalink: /tag/:name/



name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge  #pygments
logo: false
paginate: 15
baseurl: /kasper
domain_name: 'http://snowdj.github.io/kasper'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://snowdj.github.io/kasper'
author:         'Your Name'
